name: Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Build application
        run: pnpm build
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}

      - name: Start Next.js server
        run: pnpm start &
        env:
          NODE_ENV: production

      - name: Wait for Next.js to be ready
        run: npx wait-on http://localhost:3000

      - name: Install Lighthouse CI and Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npm install -g @lhci/cli@0.11.x

      - name: Run Lighthouse CI
        continue-on-error: true
        run: lhci autorun
        env:
          CHROME_PATH: /usr/bin/chromium-browser
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
